    # Generated by Django 6.0.3 on 2026-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_Cdate",
            field=models.DateField(auto_now=True),
        ),
    ]
